[Look&Feel] Fit and Finishes Changes for Security Analytics
opensearch-project/security-analytics-dashboards-plugin pull request #1147
Opened 2024-09-06 22:03 UTC by danieldong51

### Description
This PR applies the following fit and finish changes to the Security Analytics plugin:
1. Semantic Header Sizes: 
  a. H1: For page header (handled centrally) or page titles without a page header (these shouldn’t exist)
  b. H2: For headings immediately under H1s, Modal and Flyout titles, top level Panel titles
  c. H3: For headings immediately below H2s
2. Text Sizes: Using EuiText size="s"
3. Context Menus: Using small context menus
4. Tabs: Using small tabs
5. Panels: Maintaining margin sizes

### Screenshots

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-09-07 02:57 UTC, AMoo-Miki approved these changes
Thanks Dan; looks good.

Unrelated to your PR: i find it concerning that there seems to be no use of i18n in this plugin.

2024-09-07 04:10 UTC, riysaxen-amzn approved these changes

2024-09-07 16:07 UTC, amsiglan commented
> Thanks Dan; looks good.
> 
> Unrelated to your PR: i find it concerning that there seems to be no use of i18n in this plugin.

I have it in my backlog to complete this

2024-09-07 16:07 UTC, amsiglan approved these changes

2024-09-07 16:09 UTC, amsiglan requested changes
Cypress tests need to be updated after these changes

2024-09-09 17:08 UTC, AWSHurneyt approved these changes

2024-09-09 19:14 UTC, amsiglan approved these changes

2024-09-09 23:50 UTC, merged